version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongui-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mongui-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  mongui-network:
    driver: bridge

